# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Matteo Paltenghi
tagline:          Research Scientist in AI and Quantum
description:      Research Scientist in AI and Quantum
url:              matteopaltenghi.com
#baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.


author:
  name:           'Matteo Paltenghi'
  url:            https://www.linkedin.com/in/matteo-paltenghi/

#paginate:         5
#paginate_path:      '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

back_page: null

plugins:
#  - jekyll-feed
  - jekyll-gist
#  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
